trigger:
- development

stages:
# Build and Test Stage
- stage: Build
  displayName: 'Build and Test Stage'
  jobs:
  - job: BuildAndTest
    displayName: 'Install and Run Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Set Up Python 3.x'

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Upgrade Pip'

    - script: |
        python -m unittest test_todo.py
      displayName: 'Run Unit Tests'

# Deploy to Test Environment
- stage: DeployToTest
  displayName: 'Deploy to Test Environment'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: TestDeploy
    displayName: 'Deploy to Test'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying To-Do List App to Test Environment"
            displayName: 'Deploy Step'

# Deploy to Production Environment (with Approval)
- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToTest
  condition: succeeded()
  jobs:
  - deployment: ProdDeploy
    displayName: 'Deploy to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying To-Do List App to Production Environment"
            displayName: 'Deploy Step'
